### ISSUE TITLE
关于<4.5 从服务端获取数据>一节92页第二行jQuery的this作用域描述不太恰当。

### ISSUE THREAD

**Issue by tangdaohai** [DotNetAge/vue-in-action#1]
```
   //...
  created(){
     var self = this
    $.get('/api/home').then(res => {
          //... 对self赋值
    })
 }
```
这句描述的不太恰当

> 我们需要用一个self变量来“hold”住当前的vue对象实例,这未免显得代码很糟糕。

因为`then` 的参数是一个 `箭头函数` 所以其中的this指向的与self是完全相等的。

**Comment by tangdaohai** [comment]
所以在93页的底部:

> vue-resouce 的最大好处是它会自动为我们在异步成功调用后将Vue实例注入到回调方法中

这种说法好像不太准确的, 因为这完全归功与`箭头函数没有独自作用域`的功劳

**Comment by DotNetAge** [comment]
@tangdaohai 首先，非常感谢你详细地指出书中的错误，就此问题我也重新仔细地查阅了ES6的语言规范，确实书中写得不太恰当，未免是停留在 ES5 上了。

> 普通function函数和箭头函数的行为有一个微妙的区别，箭头函数没有它自己的this值，箭头函数内的this值继承自外围作用域。

我会将此勘误归入一下印刷版本中的。
