### ISSUE TITLE
大哥你确定书中的代码都有运行过的？

### ISSUE THREAD

**Issue by dragon8github** [DotNetAge/vue-in-action#3]
其他就不说了。P123页中。创建一个简单的spy辅助函数处。
const spy = () => { //...  }  这里不可以使用箭头函数吧。不然argumrnet衡指向外部的arguments。也就是sum函数……
唉~

**Comment by DotNetAge** [comment]
嗯，示例代码都是跑通的。但书中其它部分的一些举例性的代码意在说明其中原理就没有一个一个地去跑了，这难免会有小Bug或者笔误，还请见谅。毕竟写书也是一个迭代的过程，也多得有了你们这样热心的推动这些小Bug会慢慢被我根除的。

你这个问题确实是一个笔误了，确实不能使用箭头方法，应该直接使用闭包函数返回

```js
function createSpy(targetFunc) {
  function spy() {
      spy.args = arguments;
      spy.returnValue = targetFunc.apply(this, arguments);
      return spy.returnValue;
  }
}
```
