### ISSUE TITLE
你想在第六章的6.3想说啥，可否直接跳过垃圾的6.3这一节

### ISSUE THREAD

**Issue by king188166** [DotNetAge/vue-in-action#5]
第一，你的第六章写的很不好，我硬着头皮看6.3的，看不懂越看越恼火，很多文字和配图代码感觉没有关系，我努力地找关系，但是还是不懂。P182的那个文字说的和代码显示的都是两码事。我是没有信心看了，
       第二，我刚要看6.4的时候P211,"首先，设计这个表单组建的用法接口"这句话说完，下面配的是你提到很多次的测试的格式。请问这是接口还是测试？
       第三，为啥介绍到后面JSX都出来了，那不是React的吗？又详细的说React常用的render,我觉得介绍vue的template还是多些好，这样很容易混淆?

**Comment by DotNetAge** [comment]
JSX 和Render方法就是Vue2的渲染核心
