### ISSUE TITLE
老师您好，关于多入口的问题，想请教！

### ISSUE THREAD

**Issue by cys85** [DotNetAge/vue-in-action#6]
老师所推荐的多入口的方式是其他vue实例中没有提及的，看后感觉与我当前项目非常吻合，但是关于多入口有点疑惑，多入口后的 管理端的 router、store 和APP端的 router、store 是采用 公用模式，还是 后台管理用后台管理 的router 和 store ，app前台 用前台的 router 和 store呢，望老师给予解惑

**Comment by DotNetAge** [comment]
在我最初遇到这个问题时我也有与你同样的困惑，但其实只要你细想一想这个问题就很好理解。其实前台、后前只不过是我们按**使用功能**进行分隔的，一个Web应用可以没有前台也可以没有后台对不？换句话说前台与后台本来就可以是独立存在单独运行的。所以只要将前台和后台单独看作一个独立的应用那么这一切就解决了，每一个入口都是一个独立的Vue 实例入口，每个Vue实例入口就有独立的 store 和 router，不知道这样解释是否能清楚。

**Comment by cys85** [comment]
@DotNetAge 懂了
